# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Amount(BaseModel):
    """
    Amount
    """ # noqa: E501
    amount_value: Union[Annotated[float, Field(strict=True)], Annotated[int, Field(strict=True)]] = Field(description="The amount given with fractional digits, where fractions must be compliant to the currency definition. Negative amounts are signed by minus. The decimal separator is a dot.  **Example:** Valid representations for EUR with up to two decimals are:    * 1056   * 5768.2   * -1.50   * 5877.78 ", alias="amountValue")
    currency: Annotated[str, Field(strict=True)] = Field(description="ISO 4217 Alpha 3 currency code. ")
    __properties: ClassVar[List[str]] = ["amountValue", "currency"]


