# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from tatrapayplus.models.color_attribute import ColorAttribute
from typing import Optional, Set
from typing_extensions import Self

class AppearanceRequest(BaseModel):
    """
    Attributes that can be customised
    """ # noqa: E501
    theme: Optional[StrictStr] = 'SYSTEM'
    tint_on_accent: Optional[ColorAttribute] = Field(default=None, alias="tintOnAccent")
    tint_accent: Optional[ColorAttribute] = Field(default=None, alias="tintAccent")
    surface_accent: Optional[ColorAttribute] = Field(default=None, alias="surfaceAccent")
    __properties: ClassVar[List[str]] = ["theme", "tintOnAccent", "tintAccent", "surfaceAccent"]


