# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from tatrapayplus.models.payment_method import PaymentMethod
from typing import Optional, Set
from typing_extensions import Self

class AvailablePaymentMethod(BaseModel):
    """
    AvailablePaymentMethod
    """ # noqa: E501
    payment_method: PaymentMethod = Field(alias="paymentMethod")
    is_available: StrictBool = Field(description="if true, method will be shown to user. Otherwise reasonCode will be provided", alias="isAvailable")
    reason_code_method_availability: Optional[StrictStr] = Field(default=None, description="reason code. List of enumaration will be provided in documentation", alias="reasonCodeMethodAvailability")
    reason_code_method_availability_description: Optional[StrictStr] = Field(default=None, description="reason code description", alias="reasonCodeMethodAvailabilityDescription")
    __properties: ClassVar[List[str]] = ["paymentMethod", "isAvailable", "reasonCodeMethodAvailability", "reasonCodeMethodAvailabilityDescription"]


