# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BankTransferStatus(str, Enum):
    """
    The transaction status is filled with codes of the ISO 20022 
    """

    """
    allowed enum values
    """
    ACCC = 'ACCC'
    ACCP = 'ACCP'
    ACSC = 'ACSC'
    ACSP = 'ACSP'
    ACTC = 'ACTC'
    ACWC = 'ACWC'
    ACWP = 'ACWP'
    RCVD = 'RCVD'
    PDNG = 'PDNG'
    RJCT = 'RJCT'
    CANC = 'CANC'
    ACFC = 'ACFC'
    PATC = 'PATC'
    PART = 'PART'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BankTransferStatus from a JSON string"""
        return cls(json.loads(json_str))


