# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from tatrapayplus.models.address import Address
from tatrapayplus.models.card_identifier_or_register import CardIdentifierOrRegister
from typing import Optional, Set
from typing_extensions import Self

class CardDetail(BaseModel):
    """
    Card pay information
    """ # noqa: E501
    card_pay_lang_override: Optional[StrictStr] = Field(default=None, description="It is possible to override the accept-language header for the CardPay payment method. This override only affects CardPay itself, not the whole TatraPayPlus service.  If it is empty , then accept-language is taken into account ", alias="cardPayLangOverride")
    is_pre_authorization: Optional[StrictBool] = Field(default=None, description="If true - pre-authorization transaction", alias="isPreAuthorization")
    card_holder: Annotated[str, Field(min_length=2, strict=True, max_length=45)] = Field(description="The card holder name. In case of Direct API either cardHolder or email is mandatory", alias="cardHolder")
    billing_address: Optional[Address] = Field(default=None, alias="billingAddress")
    shipping_address: Optional[Address] = Field(default=None, alias="shippingAddress")
    comfort_pay: Optional[CardIdentifierOrRegister] = Field(default=None, alias="comfortPay")
    __properties: ClassVar[List[str]] = ["cardPayLangOverride", "isPreAuthorization", "cardHolder", "billingAddress", "shippingAddress", "comfortPay"]


