# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CardPayStatus(str, Enum):
    """
     **CardPay status**  | Enum      | description | | ---------------- | ------------| | INIT              | initialized transaction     | | OK              | processed successfully transaction     | | FAIL              | failed transaction | | PA              | pre-authorization | | CPA              | completed pre-authorization | | SPA               | canceled preauthorization | | XPA               | expired pre-authorization | | CB               | returned payment | | AUTH_REQUIRED               | 3D secure authorization required | | AUTH_EXPIRED               | authorization expired | | AUTH_CANCELED               | authorization canceled | 
    """

    """
    allowed enum values
    """
    INIT = 'INIT'
    OK = 'OK'
    FAIL = 'FAIL'
    PA = 'PA'
    CPA = 'CPA'
    SPA = 'SPA'
    XPA = 'XPA'
    CB = 'CB'
    AUTH_REQUIRED = 'AUTH_REQUIRED'
    AUTH_EXPIRED = 'AUTH_EXPIRED'
    AUTH_CANCELED = 'AUTH_CANCELED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CardPayStatus from a JSON string"""
        return cls(json.loads(json_str))


