# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from tatrapayplus.models.card_pay_amount import CardPayAmount
from tatrapayplus.models.card_pay_status import CardPayStatus
from tatrapayplus.models.card_pay_status_structure_comfort_pay import CardPayStatusStructureComfortPay
from tatrapayplus.models.direct_transaction_data_reason_code import DirectTransactionDataReasonCode
from typing import Optional, Set
from typing_extensions import Self

class CardPayStatusStructure(BaseModel):
    """
    card pay status structure
    """ # noqa: E501
    status: CardPayStatus
    currency: Annotated[str, Field(strict=True)] = Field(description="ISO 4217 Alpha 3 currency code. ")
    amount: Optional[Union[Annotated[float, Field(strict=True)], Annotated[int, Field(strict=True)]]] = Field(default=None, description="The amount given with fractional digits, where fractions must be compliant to the currency definition. Negative amounts are signed by minus. The decimal separator is a dot.  **Example:** Valid representations for EUR with up to two decimals are:    * 1056   * 5768.2   * -1.50   * 5877.78 ")
    pre_authorization: Optional[CardPayAmount] = Field(default=None, alias="preAuthorization")
    charge_back: Optional[CardPayAmount] = Field(default=None, alias="chargeBack")
    comfort_pay: Optional[CardPayStatusStructureComfortPay] = Field(default=None, alias="comfortPay")
    masked_card_number: Optional[Annotated[str, Field(strict=True, max_length=19)]] = Field(default=None, description="Masked card number.", alias="maskedCardNumber")
    reason_code: Optional[DirectTransactionDataReasonCode] = Field(default=None, alias="reasonCode")
    payment_authorization_code: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Payment authorization code", alias="paymentAuthorizationCode")
    __properties: ClassVar[List[str]] = ["status", "currency", "amount", "preAuthorization", "chargeBack", "comfortPay", "maskedCardNumber", "reasonCode", "paymentAuthorizationCode"]


