# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ColorAttribute(BaseModel):
    """
    Color attributes for specific theme. Choose colour with sufficient contrast for the specific theme
    """ # noqa: E501
    color_dark_mode: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Hexadecimal value of the color", alias="colorDarkMode")
    color_light_mode: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Hexadecimal value of the color", alias="colorLightMode")
    __properties: ClassVar[List[str]] = ["colorDarkMode", "colorLightMode"]


