# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from tatrapayplus.models.direct_transaction_data_reason_code import DirectTransactionDataReasonCode
from typing import Optional, Set
from typing_extensions import Self

class DirectTransactionData(BaseModel):
    """
    DirectTransactionData
    """ # noqa: E501
    reason_code: Optional[DirectTransactionDataReasonCode] = Field(default=None, alias="reasonCode")
    payment_authorization_code: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Payment authorization code", alias="paymentAuthorizationCode")
    __properties: ClassVar[List[str]] = ["reasonCode", "paymentAuthorizationCode"]


