# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DirectTransactionIPSPData(BaseModel):
    """
    DirectTransactionIPSPData
    """ # noqa: E501
    sub_merchant_id: Annotated[str, Field(strict=True)] = Field(alias="subMerchantId")
    name: Annotated[str, Field(strict=True)]
    location: Annotated[str, Field(strict=True)]
    country: Annotated[str, Field(strict=True)] = Field(description="ISO 3166 ALPHA2 country code.")
    __properties: ClassVar[List[str]] = ["subMerchantId", "name", "location", "country"]


