# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from tatrapayplus.models.available_payment_method import AvailablePaymentMethod
from typing import Optional, Set
from typing_extensions import Self

class InitiatePaymentResponse(BaseModel):
    """
    InitiatePaymentResponse
    """ # noqa: E501
    payment_id: StrictStr = Field(description="Payment intent identifier", alias="paymentId")
    tatra_pay_plus_url: Optional[StrictStr] = Field(default=None, description="URL address for FE redirect to tatraPayPlus app", alias="tatraPayPlusUrl")
    available_payment_methods: Optional[List[AvailablePaymentMethod]] = Field(default=None, description="List of availibility of each possible methods.", alias="availablePaymentMethods")
    __properties: ClassVar[List[str]] = ["paymentId", "tatraPayPlusUrl", "availablePaymentMethods"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InitiatePaymentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_payment_methods (list)
        _items = []
        if self.available_payment_methods:
            for _item_available_payment_methods in self.available_payment_methods:
                if _item_available_payment_methods:
                    _items.append(_item_available_payment_methods.to_dict())
            _dict['availablePaymentMethods'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InitiatePaymentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentId": obj.get("paymentId"),
            "tatraPayPlusUrl": obj.get("tatraPayPlusUrl"),
            "availablePaymentMethods": [AvailablePaymentMethod.from_dict(_item) for _item in obj["availablePaymentMethods"]] if obj.get("availablePaymentMethods") is not None else None
        })
        return _obj


