# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from tatrapayplus.models.bank_transfer import BankTransfer
from tatrapayplus.models.base_payment import BasePayment
from tatrapayplus.models.card_detail import CardDetail
from tatrapayplus.models.pay_later import PayLater
from tatrapayplus.models.user_data import UserData
from typing import Optional, Set
from typing_extensions import Self

class InitiatePaymentRequest(BaseModel):
    """
    Body for payment initiation
    """ # noqa: E501
    base_payment: BasePayment = Field(alias="basePayment")
    user_data: Optional[UserData] = Field(default=None, alias="userData")
    bank_transfer: Optional[BankTransfer] = Field(default=None, alias="bankTransfer")
    card_detail: Optional[CardDetail] = Field(default=None, alias="cardDetail")
    pay_later: Optional[PayLater] = Field(default=None, alias="payLater")
    __properties: ClassVar[List[str]] = ["basePayment", "userData", "bankTransfer", "cardDetail", "payLater"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InitiatePaymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_payment
        if self.base_payment:
            _dict['basePayment'] = self.base_payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_data
        if self.user_data:
            _dict['userData'] = self.user_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bank_transfer
        if self.bank_transfer:
            _dict['bankTransfer'] = self.bank_transfer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of card_detail
        if self.card_detail:
            _dict['cardDetail'] = self.card_detail.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pay_later
        if self.pay_later:
            _dict['payLater'] = self.pay_later.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InitiatePaymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "basePayment": BasePayment.from_dict(obj["basePayment"]) if obj.get("basePayment") is not None else None,
            "userData": UserData.from_dict(obj["userData"]) if obj.get("userData") is not None else None,
            "bankTransfer": BankTransfer.from_dict(obj["bankTransfer"]) if obj.get("bankTransfer") is not None else None,
            "cardDetail": CardDetail.from_dict(obj["cardDetail"]) if obj.get("cardDetail") is not None else None,
            "payLater": PayLater.from_dict(obj["payLater"]) if obj.get("payLater") is not None else None
        })
        return _obj


