# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from tatrapayplus.models.available_payment_method import AvailablePaymentMethod
from typing import Optional, Set
from typing_extensions import Self

class Model400ErrorBody(BaseModel):
    """
    Model400ErrorBody
    """ # noqa: E501
    error_code: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias="errorCode")
    error_description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, alias="errorDescription")
    available_payment_methods: Optional[List[AvailablePaymentMethod]] = Field(default=None, description="Reason codes of declined methods", alias="availablePaymentMethods")
    __properties: ClassVar[List[str]] = ["errorCode", "errorDescription", "availablePaymentMethods"]


