# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from tatrapayplus.models.item_detail import ItemDetail
from typing import Optional, Set
from typing_extensions import Self

class OrderItem(BaseModel):
    """
    OrderItem
    """ # noqa: E501
    quantity: StrictInt = Field(description="Quantity of the item")
    total_item_price: Union[StrictFloat, StrictInt] = Field(description="Total item price (including quantity e.g.:(item price*quantity))", alias="totalItemPrice")
    item_detail: ItemDetail = Field(alias="itemDetail")
    item_info_url: Optional[StrictStr] = Field(default=None, alias="itemInfoURL")
    item_image: Optional[Annotated[str, Field(strict=True, max_length=1000000)]] = Field(default=None, description="base64 encoded image h:48px w:48px", alias="itemImage")
    __properties: ClassVar[List[str]] = ["quantity", "totalItemPrice", "itemDetail", "itemInfoURL", "itemImage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of item_detail
        if self.item_detail:
            _dict['itemDetail'] = self.item_detail.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quantity": obj.get("quantity"),
            "totalItemPrice": obj.get("totalItemPrice"),
            "itemDetail": ItemDetail.from_dict(obj["itemDetail"]) if obj.get("itemDetail") is not None else None,
            "itemInfoURL": obj.get("itemInfoURL"),
            "itemImage": obj.get("itemImage")
        })
        return _obj


