# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PayLaterStatus(str, Enum):
    """
    Finance application status
    """

    """
    allowed enum values
    """
    NEW = 'NEW'
    CUSTOMER_CREATION_IN_PROGRESS = 'CUSTOMER_CREATION_IN_PROGRESS'
    LOAN_APPLICATION_IN_PROGRESS = 'LOAN_APPLICATION_IN_PROGRESS'
    LOAN_APPLICATION_FINISHED = 'LOAN_APPLICATION_FINISHED'
    LOAN_DISBURSED = 'LOAN_DISBURSED'
    CANCELED = 'CANCELED'
    EXPIRED = 'EXPIRED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PayLaterStatus from a JSON string"""
        return cls(json.loads(json_str))


