# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from tatrapayplus.models.payment_intent_status_response_status import PaymentIntentStatusResponseStatus
from tatrapayplus.models.payment_method import PaymentMethod
from typing import Optional, Set
from typing_extensions import Self

class PaymentIntentStatusResponse(BaseModel):
    """
     **TatraPayPlus status response. For each payment method will be sent specific status structure**  | selectedPaymentMethod      | status structure | description| | ---------------- | ------------| ------------| | BANK_TRANSFER              | bankTransferStatus     || | QR_PAY                   | bankTransferStatus     | Only ACCC is provided. Status will be provided as soon as amount is in target account | | CARD_PAY              | cardPayStatusStructure || | PAY_LATER               | payLaterStatus || | DIRECT_API               | cardPayStatusStructure || 
    """ # noqa: E501
    selected_payment_method: Optional[PaymentMethod] = Field(default=None, alias="selectedPaymentMethod")
    authorization_status: StrictStr = Field(description="Status of payment intent authorization progress. Be aware, It doesnt indicate payment status! To get payment status see attribute status.", alias="authorizationStatus")
    status: Optional[PaymentIntentStatusResponseStatus] = None
    __properties: ClassVar[List[str]] = ["selectedPaymentMethod", "authorizationStatus", "status"]


