# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from tatrapayplus.models.amount_range_rule import AmountRangeRule
from tatrapayplus.models.payment_method import PaymentMethod
from tatrapayplus.models.provider import Provider
from typing import Optional, Set
from typing_extensions import Self

class PaymentMethodRules(BaseModel):
    """
    PaymentMethodRules
    """ # noqa: E501
    payment_method: PaymentMethod = Field(alias="paymentMethod")
    amount_range_rule: Optional[AmountRangeRule] = Field(default=None, alias="amountRangeRule")
    supported_currency: Optional[List[Annotated[str, Field(strict=True)]]] = Field(default=None, alias="supportedCurrency")
    supported_country: Optional[List[Annotated[str, Field(strict=True)]]] = Field(default=None, description="Payment method is applicable for payment to listed countries", alias="supportedCountry")
    allowed_bank_providers: Optional[List[Provider]] = Field(default=None, description="Allowed bank providers for BANK_TRNASFER method selected by TatraPayPlus client", alias="allowedBankProviders")
    __properties: ClassVar[List[str]] = ["paymentMethod", "amountRangeRule", "supportedCurrency", "supportedCountry", "allowedBankProviders"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentMethodRules from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount_range_rule
        if self.amount_range_rule:
            _dict['amountRangeRule'] = self.amount_range_rule.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in allowed_bank_providers (list)
        _items = []
        if self.allowed_bank_providers:
            for _item_allowed_bank_providers in self.allowed_bank_providers:
                if _item_allowed_bank_providers:
                    _items.append(_item_allowed_bank_providers.to_dict())
            _dict['allowedBankProviders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentMethodRules from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "paymentMethod": obj.get("paymentMethod"),
            "amountRangeRule": AmountRangeRule.from_dict(obj["amountRangeRule"]) if obj.get("amountRangeRule") is not None else None,
            "supportedCurrency": obj.get("supportedCurrency"),
            "supportedCountry": obj.get("supportedCountry"),
            "allowedBankProviders": [Provider.from_dict(_item) for _item in obj["allowedBankProviders"]] if obj.get("allowedBankProviders") is not None else None
        })
        return _obj


