# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PaymentSymbols(BaseModel):
    """
    PaymentSymbols
    """ # noqa: E501
    variable_symbol: Annotated[str, Field(strict=True)] = Field(alias="variableSymbol")
    specific_symbol: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="specificSymbol")
    constant_symbol: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="In case of payment method CardPay will be automatically rewrite to value 0608", alias="constantSymbol")
    __properties: ClassVar[List[str]] = ["variableSymbol", "specificSymbol", "constantSymbol"]


