# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Provider(BaseModel):
    """
    Data provider
    """ # noqa: E501
    country_code: Annotated[str, Field(strict=True)] = Field(description="ISO 3166 ALPHA2 country code.", alias="countryCode")
    provider_name: Annotated[str, Field(strict=True, max_length=500)] = Field(alias="providerName")
    provider_code: Annotated[str, Field(strict=True, max_length=50)] = Field(alias="providerCode")
    swift_code: Annotated[str, Field(strict=True)] = Field(description="BICFI ", alias="swiftCode")
    __properties: ClassVar[List[str]] = ["countryCode", "providerName", "providerCode", "swiftCode"]


