# coding: utf-8

"""
    TatraPayPlus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1_2024-05-27v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UserData(BaseModel):
    """
    UserData
    """ # noqa: E501
    external_applicant_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="External applicant ID, could be generated by application", alias="externalApplicantId")
    first_name: Annotated[str, Field(min_length=1, strict=True, max_length=30)] = Field(alias="firstName")
    last_name: Annotated[str, Field(min_length=1, strict=True, max_length=30)] = Field(alias="lastName")
    email: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Conditionally mandatory. In case of TatraPayPlus payment initiation - It is mandatory only if the phone attribute is not provided. If the email is not provided, the user will not receive the cardPay notification and payLater will ask for the email in the app. In case of Direct API either cardHolder or email is mandatory")
    phone: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Conditionally mandatory.  In case of TatraPayPlus payment initiation - It is mandatory only if the email attribute is not provided.")
    __properties: ClassVar[List[str]] = ["externalApplicantId", "firstName", "lastName", "email", "phone"]


