name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TATRAPAY_CLIENT_ID: ${{ secrets.TATRAPAY_CLIENT_ID }}
      TATRAPAY_CLIENT_SECRET: ${{ secrets.TATRAPAY_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .     
          pip install pytest 

      - name: Run tests
        run: pytest
